version: '3.2'

services:
  web:
    build: .
    depends_on:
      - db
      - npm-build
    env_file:
      - provision/.env
    volumes:
      - .:/restaurant-vote
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
    command: >
      sh -c "
        while [ ! -f 'frontend/build/index.html' ]
        do
          echo 'Waiting for frontend build to become ready...'; sleep 5;
        done;
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
  db:
    image: postgres:12.2
    restart: always
    env_file:
      - provision/.env
    ports:
      - "5432:5432"
    volumes:
      - ./provision/db:/docker-entrypoint-initdb.d
      - postgres-db:/var/lib/postgresql/data
  npm-build:
    image: node:14.1
    command: >
      sh -c "
        cd restaurant-vote/frontend &&
        npm install &&
        npm run build
      "
    volumes:
      - .:/restaurant-vote

volumes:
  postgres-db:

